### ISSUE TITLE
Physics roadmap 

### ISSUE THREAD

**Issue by streeve** [ORNL/CabanaPD#112]
- Contact physics 
  - [ ] Initial #59 
  - [ ] Distributed contact
  - [ ] Recreate example with separate bodies
- [ ] Multi-material (see #109)
- [ ] Per-particle stress calculation
